
name: Tidelift Alignment
on:
  schedule:
    - cron: "30 2 * * *"  # daily at 02:30 UTC
  push:
    paths:
      - ".github/workflows/tidelift.yml"

  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'celery'
    name: Ensure approved open source packages are in use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan
        uses: tidelift/alignment-action@main
        env:
          TIDELIFT_API_KEY: ${{ secrets.TIDELIFT_API_KEY }}
          TIDELIFT_ORGANIZATION: team/auvipy
          TIDELIFT_PROJECT: celeryproject
